name: Run Databricks Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests>=2.28.0
        
    - name: Run Databricks Job (Hello World)
      env:
        DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        python -V
        pwd
        ls -la
        python create_and_run_job.py
        echo "Job has been triggered successfully." 
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          
    - name: Job Status Check
      if: always()
      run: |
        echo "Job execution completed. Check the logs above for results."
######